import { createFileRoute } from "@tanstack/react-router";
import { ProvenanceTag } from "@/components/raceiq/ProvenanceTag";
import { POSTURE_STYLE } from "@/components/raceiq/MatchupCard";
import type { Posture } from "@/lib/raceiq/contracts";
import {
  EMPTY,
  fmtClock,
  fmtGap,
  fmtPct,
  fmtSeconds,
  fmtPosition,
} from "@/lib/raceiq/format";
import { useRaceIQ } from "@/lib/raceiq/store";

export const Route = createFileRoute("/what-if")({
  head: () => ({
    meta: [
      { title: "What If — RaceIQ" },
      {
        name: "description",
        content:
          "Pause the replay and inspect what the RaceIQ recommended action projects. History stays untouched.",
      },
      { property: "og:title", content: "What If — RaceIQ" },
      {
        name: "og:description",
        content: "Counterfactual race projection seeded from an untouched replay state.",
      },
    ],
  }),
  component: WhatIf,
});

function WhatIf() {
  const {
    snapshot,
    circuit,
    selected,
    setSelected,
    pause,
    playing,
    time,
    driver: driverOf,
    stateOf,
    recommendationFor,
    whatIf,
  } = useRaceIQ();

  const state = stateOf(selected);
  const driver = driverOf(selected);
  const ahead = snapshot.drivers.find((d) => d.position === (state?.position ?? 0) - 1);

  const rec = recommendationFor(selected);
  const recommendedPosture: Posture | undefined = rec?.posture;
  const branch = recommendedPosture ? whatIf(selected, recommendedPosture) : undefined;

  return (
    <main className="mx-auto max-w-[1200px] px-4 py-6 sm:px-6">
      <h1 className="text-xl font-semibold sm:text-2xl">What if?</h1>
      <p className="mt-1 max-w-2xl text-sm text-muted-foreground">
        Projected outcome if the RaceIQ recommendation is followed. The race state is frozen
        and counterfactual projections are generated by Tier-2 MPC. History remains untouched.
      </p>

      <div className="mt-5 grid gap-4 lg:grid-cols-2">
        {/* FROZEN RACE STATE (SEED) */}
        <section className="panel p-4">
          <div className="flex items-center justify-between gap-2">
            <p className="eyebrow">Frozen race state (seed)</p>
            <ProvenanceTag kind={snapshot.positionsProvenance} />
          </div>
          <dl className="mt-3 grid grid-cols-2 gap-3">
            {[
              { k: "Circuit", v: circuit.event },
              { k: "Lap", v: `${snapshot.lap}/${snapshot.totalLaps}` },
              { k: "Race clock", v: fmtClock(time) },
              { k: "Driver", v: `${selected}${driver.team ? ` — ${driver.team}` : ""}` },
              { k: "Position", v: fmtPosition(state?.position) },
              { k: "Gap ahead", v: state?.position === 1 ? EMPTY : fmtGap(state?.gapAhead, 2) },
              { k: "Battery (est.)", v: fmtPct(state?.soc) },
              { k: "Car ahead", v: ahead ? `${ahead.code} (P${ahead.position})` : "none" },
            ].map((i) => (
              <div key={i.k}>
                <dt className="text-[11px] text-muted-foreground">{i.k}</dt>
                <dd className="data text-sm">{i.v}</dd>
              </div>
            ))}
          </dl>
          <div className="mt-4 flex flex-wrap items-center gap-2 border-t border-border pt-3">
            <select
              value={selected}
              onChange={(e) => setSelected(e.target.value)}
              aria-label="Driver"
              className="data rounded-md border border-border bg-surface-raised px-2 py-1 text-xs"
            >
              {snapshot.drivers.map((d) => (
                <option key={d.code} value={d.code}>
                  P{d.position} {d.code}
                </option>
              ))}
            </select>
            <button
              type="button"
              onClick={pause}
              disabled={!playing}
              className="data rounded-md border border-border px-2 py-1 text-xs text-muted-foreground transition-colors hover:bg-accent disabled:opacity-40"
            >
              {playing ? "FREEZE REPLAY" : "REPLAY FROZEN"}
            </button>
          </div>
          <p className="mt-3 border-t border-border/60 pt-2 text-[10px] text-muted-foreground">
            Tier-2 MPC evaluated 4 strategic postures (ATTACK, HOLD, DEFEND, HARVEST) from this frozen race state.
          </p>
        </section>

        {/* RACEIQ RECOMMENDATION & PROJECTED RESULT */}
        <section className="panel p-4">
          <div className="flex items-center justify-between gap-2">
            <p className="eyebrow">RaceIQ recommends</p>
            <ProvenanceTag kind="PROJECTED" />
          </div>

          {recommendedPosture ? (
            <>
              {/* RECOMMENDED POSTURE BANNER */}
              <div className="mt-3 flex items-center justify-between border-b border-border pb-3">
                <div className="flex items-center gap-3">
                  <span
                    className={`data rounded border px-3 py-1 text-sm font-bold tracking-[0.16em] ${POSTURE_STYLE[recommendedPosture]}`}
                  >
                    {recommendedPosture}
                  </span>
                  <span className="text-xs text-muted-foreground">
                    {rec?.reason ?? "Optimal strategic posture derived from model evaluation."}
                  </span>
                </div>
                {branch?.score !== undefined && (
                  <div className="text-right">
                    <span className="text-[10px] tracking-widest text-muted-foreground">MODEL SCORE</span>
                    <p className="data text-sm font-semibold tabular-nums text-foreground">
                      {branch.score > 0 ? `+${branch.score.toFixed(2)}` : branch.score.toFixed(2)}
                    </p>
                  </div>
                )}
              </div>

              {/* PROJECTED RESULT */}
              <div className="mt-4">
                <p className="eyebrow">Projected result</p>
                <dl className="mt-2 grid grid-cols-2 gap-3">
                  {[
                    { k: "Projected position", v: fmtPosition(branch?.projectedPosition) },
                    { k: "Projected gap", v: fmtSeconds(branch?.projectedGap, 2) },
                    { k: "Projected battery", v: fmtPct(branch?.projectedSoc) },
                    {
                      k: "Energy effect",
                      v:
                        typeof branch?.energySpendMj === "number"
                          ? `${branch.energySpendMj > 0 ? "+" : ""}${branch.energySpendMj.toFixed(2)} MJ`
                          : EMPTY,
                    },
                    {
                      k: "Minimum battery",
                      v:
                        typeof branch?.minSocMj === "number"
                          ? `${branch.minSocMj.toFixed(2)} MJ (${fmtPct(branch.minSocMj / 4.0)})`
                          : EMPTY,
                    },
                    {
                      k: "Strategic model score",
                      v:
                        branch?.score !== undefined
                          ? branch.score.toFixed(2)
                          : EMPTY,
                    },
                    { k: "Risk", v: branch?.risk ?? EMPTY },
                    {
                      k: "Passes / re-passes",
                      v:
                        typeof branch?.passesAhead === "number" &&
                        typeof branch?.repassesBehind === "number"
                          ? `${branch.passesAhead} / ${branch.repassesBehind}`
                          : EMPTY,
                    },
                    {
                      k: "Evaluation horizon",
                      v:
                        typeof branch?.horizonLaps === "number"
                          ? `${branch.horizonLaps} laps`
                          : EMPTY,
                    },
                  ].map((i) => (
                    <div key={i.k}>
                      <dt className="text-[11px] text-muted-foreground">{i.k}</dt>
                      <dd className="data text-sm text-projected">{i.v}</dd>
                    </div>
                  ))}
                </dl>
              </div>

              {/* MODEL OUTCOME */}
              <div className="mt-4 border-t border-border pt-3">
                <p className="eyebrow">Model outcome</p>
                <div className="mt-2 rounded border border-border bg-surface-raised/60 p-3 text-xs">
                  {branch?.outcome ? (
                    <p className="leading-relaxed text-foreground/90">{branch.outcome}</p>
                  ) : (
                    <p className="text-muted-foreground">
                      No model-generated projection available for this state.
                    </p>
                  )}
                  {branch?.inputsUnavailable && branch.inputsUnavailable.length > 0 && (
                    <p className="mt-2 border-t border-border/50 pt-2 text-[10px] text-muted-foreground">
                      Inputs unavailable for this projection: {branch.inputsUnavailable.join(", ")} (not fabricated).
                    </p>
                  )}
                </div>
              </div>
            </>
          ) : (
            <div className="mt-6 rounded border border-border/60 bg-surface-raised/40 p-4 text-center">
              <p className="text-xs text-muted-foreground">
                No active recommendation available for {selected} at this moment in the race.
              </p>
            </div>
          )}
        </section>
      </div>

      <p className="data mt-4 rounded-xl border border-projected/40 bg-projected/10 p-3 text-[11px] text-projected">
        BRANCH SEED · {(branch?.seed.circuitId ?? snapshot.circuitId).toUpperCase()} / LAP{" "}
        {branch?.seed.lap ?? snapshot.lap} / T{(branch?.seed.time ?? snapshot.time).toFixed(1)}s /{" "}
        {branch?.seed.driver ?? selected} {fmtPosition(branch?.seed.position ?? state?.position)} —
        the seed is immutable and the historical replay is unchanged. The displayed counterfactual branch was generated by RaceIQ's Tier-2 MPC rolling-horizon simulation from this frozen state during data preparation.
      </p>
    </main>
  );
}
