/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as LiveRouteImport } from './routes/live'
import { Route as WhatIfRouteImport } from './routes/what-if'
import { Route as WhyRouteImport } from './routes/why'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatIfRoute = WhatIfRouteImport.update({
  id: '/what-if',
  path: '/what-if',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyRoute = WhyRouteImport.update({
  id: '/why',
  path: '/why',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/impact': typeof ImpactRoute
  '/live': typeof LiveRoute
  '/what-if': typeof WhatIfRoute
  '/why': typeof WhyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/impact': typeof ImpactRoute
  '/live': typeof LiveRoute
  '/what-if': typeof WhatIfRoute
  '/why': typeof WhyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/impact': typeof ImpactRoute
  '/live': typeof LiveRoute
  '/what-if': typeof WhatIfRoute
  '/why': typeof WhyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/impact' | '/live' | '/what-if' | '/why'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/impact' | '/live' | '/what-if' | '/why'
  id: '__root__' | '/' | '/impact' | '/live' | '/what-if' | '/why'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImpactRoute: typeof ImpactRoute
  LiveRoute: typeof LiveRoute
  WhatIfRoute: typeof WhatIfRoute
  WhyRoute: typeof WhyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-if': {
      id: '/what-if'
      path: '/what-if'
      fullPath: '/what-if'
      preLoaderRoute: typeof WhatIfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why': {
      id: '/why'
      path: '/why'
      fullPath: '/why'
      preLoaderRoute: typeof WhyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImpactRoute: ImpactRoute,
  LiveRoute: LiveRoute,
  WhatIfRoute: WhatIfRoute,
  WhyRoute: WhyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
